import math
import numpy as np

'''
distance calculator

'''

# -------------functions used to calculate distances-------------


def calculate_total_distance(tour, dist_matrix) -> float:
    '''
    args: 
        tour: the path generated by solver
        dist_matrix: lookup table contains all distances between any two numbers
    '''
    # path_length = sum(distance(cities[tour[i]], cities[tour[(i + 1) % len(tour)]])for i in range(len(tour)))
    path_length = sum(dist_matrix[tour[i]][tour[(i + 1) % len(tour)]]for i in range(len(tour)))
    return path_length


def distance(city1, city2) -> float:
    '''
    args: coordinates(set) of 2 cities
    return: distance between 2 cities
    used in verify scores, solvers
    '''
    return math.sqrt((city1[0] - city2[0]) ** 2 + (city1[1] - city2[1]) ** 2)


def construct_dist_matrix(cities: list[set[float]]) -> np.ndarray:
    '''
    args:
        a list of sets, containing corrdinates of each city
            (will be returned after reading raw csv via read file helper)
    return:
        a symmetric matrix of N*N, where N is length of cities
    use np array to reduce memory cost(maybe)
    np.float32 will make infinit loop for float deviation: 
    dist = np.zeros((N, N), dtype=np.float32) <-buggy
    which i haven't fully imagine how it causes bug why but intuitively makes sense
    a normal list in python also works
    '''
    N = len(cities)
    dist = np.zeros((N, N), dtype=np.float64)
    for i in range(N):
        for j in range(i, N):
            dist[i][j] = dist[j][i] = distance(cities[i], cities[j])
    return dist


def construct_dist_matrix_smarter(cities: list[set[float]]) -> np.ndarray:
    '''
    args:
        a list of sets, containing corrdinates of each city
            (will be returned after reading raw csv via read file helper)
    return:
        a symmetric matrix of N*N, where N is length of cities

    dist[i][j] = float('inf') where i==j to avoid potential bug
    use np array to reduce memory cost(maybe)
    '''
    N = len(cities)
    dist = np.full((N, N), fill_value=np.inf, dtype=np.float64)
    for i in range(N):
        for j in range(i+1, N):
            dist[i][j] = dist[j][i] = distance(cities[i], cities[j])
    return dist
